import { apiUrl, baseUrl } from '../../util/config';

const API = `${apiUrl}/api/dataset`;

export default {
  text: 'Husholdninger',
  value: 'husholdninger',
  production: true,
  cards: [
    {
      size: 'large',
      heading: 'Husholdninger',
      map: {
        labels: ['Færre aleneboende', 'Flere aleneboende'],
        url: `${API}/husholdning-totalt-status`,
        method: 'ratio',
        series: 0,
        scale: [0.25, 0.6],
      },
      production: true,
      tabs: [
        {
          active: false,
          label: 'Andel',
          id: 'husholdning_totalt_status',
          heading: 'Husholdninger etter husholdningstype',
          template: 'a',
          method: 'ratio',
          url: `${API}/husholdning-totalt-status`,
          production: true,
        },
        {
          active: false,
          label: 'Antall',
          id: 'husholdning_totalt_status',
          template: 'a',
          method: 'value',
          url: `${API}/husholdning-totalt-status`,
          production: true,
        },
        {
          active: false,
          label: 'Historisk (andel)',
          help: 'Skifte i datagrunnlaget fra SSB mellom 2012 og 2014.',
          id: 'husholdning_totalt_historisk',
          template: 'c',
          url: `${API}/husholdning-totalt-historisk`,
          method: 'ratio',
          production: true,
        },

        {
          active: false,
          label: 'Historisk (antall)',
          help: 'Skifte i datagrunnlaget fra SSB mellom 2012 og 2014.',
          id: 'husholdning_totalt_historisk',
          template: 'c',
          url: `${API}/husholdning-totalt-historisk`,
          method: 'value',
          production: true,
        },
      ],
    },
    {
      size: 'small',
      heading: 'Husholdninger med ett barn',
      map: {
        labels: ['Færre husholdninger med ett barn', 'Flere husholdninger med ett barn'],
        url: `${API}/husholdninger-med-1-barn`,
        method: 'ratio',
        series: 0,
        scale: [0.04, 0.21],
      },
      production: true,
      tabs: [
        {
          active: false,
          label: 'Andel',
          id: 'husholdning_med_1_barn_andel',
          template: 'a',
          method: 'ratio',
          url: `${API}/husholdninger-med-1-barn`,
          production: true,
        },
        {
          active: false,
          label: 'Antall',
          id: 'husholdning_med_1_barn_antall',
          template: 'a',
          method: 'value',
          url: `${API}/husholdninger-med-1-barn`,
          production: true,
        },
      ],
    },
    {
      size: 'small',
      heading: 'Husholdninger med to barn',
      map: {
        labels: ['Færre husholdninger med to barn', 'Flere husholdninger med to barn'],
        url: `${API}/husholdninger-med-2-barn`,
        method: 'ratio',
        series: 0,
        scale: [0.025, 0.22],
      },
      production: true,
      tabs: [
        {
          active: false,
          label: 'Andel',
          id: 'husholdning_med_to_barn_andel',
          template: 'a',
          method: 'ratio',
          url: `${API}/husholdninger-med-2-barn`,
          production: true,
        },
        {
          active: false,
          label: 'Antall',
          id: 'husholdning_med_to_barn_antall',
          template: 'a',
          method: 'value',
          url: `${API}/husholdninger-med-2-barn`,
          production: true,
        },
      ],
    },
    {
      size: 'small',
      heading: 'Husholdninger med tre eller flere barn',
      map: {
        labels: ['Færre husholdninger med tre+ barn', 'Flere husholdninger med tre+ barn'],
        url: `${API}/husholdninger-med-3-barn`,
        method: 'ratio',
        series: 0,
        scale: [0, 0.15],
      },
      production: true,
      tabs: [
        {
          active: false,
          label: 'Andel',
          id: 'husholdning_med_tre_barn_andel',
          template: 'a',
          method: 'ratio',
          url: `${API}/husholdninger-med-3-barn`,
          production: true,
        },
        {
          active: false,
          label: 'Antall',
          id: 'husholdning_med_tre_barn_antall',
          template: 'a',
          method: 'value',
          url: `${API}/husholdninger-med-3-barn`,
          production: true,
        },
      ],
    },
  ],
  options: {
    kategori: 'Befolkning',
    tema: 'Husholdninger',
    bgImage: `${baseUrl}/img/husholdninger`,
    txtColor: 'rgb(245, 173, 165)',
  },
  related: ['trangboddhet', 'eierform', 'bygningstyper'],
};
