import { apiUrl, baseUrl } from '../../util/config';

const API = `${apiUrl}/api/dataset`;

export default {
  text: 'Levekårsindikatorer',
  value: 'levekaar',
  production: true,
  cards: [
    {
      size: 'large',
      heading: 'Levekår',
      production: true,
      tabs: [
        {
          production: true,
          active: true,
          label: 'Sammenlignet med Oslo',
          template: 'k',
          heading: 'Ulike levekårsindikatorer (%) sammenlignet med Oslo',
          method: 'ratio',
          mode: 'osloRatio',
          url: `${API}/levekar-totalt-status`,
        },
        {
          production: true,
          active: true,
          label: 'Sammenlignet med bydelen',
          template: 'k',
          heading: 'Ulike levekårsindikatorer (%) sammenlignet med bydelen',
          method: 'ratio',
          mode: 'districtRatio',
          url: `${API}/levekar-totalt-status`,
        },
      ],
    },
    {
      size: 'small',
      heading: 'Lav utdanning',
      map: {
        labels: ['Færre', 'Flere'],
        url: `${API}/levekar-lav-utdanning-status`,
        scale: [0, 0.5],
        reverse: true,
        method: 'ratio',
      },
      production: true,
      tabs: [
        {
          active: false,
          label: 'Andel',
          id: 'levekar_lav-utdanning_andel',
          heading: 'Personer 30–59 år med lav utdanning',
          template: 'a',
          method: 'ratio',
          url: `${API}/levekar-lav-utdanning-status`,
          production: true,
        },
        {
          active: false,
          label: 'Antall',
          id: 'levekar_lav-utdanning_andel',
          heading: 'Personer 30–59 år med lav utdanning',
          template: 'a',
          method: 'value',
          url: `${API}/levekar-lav-utdanning-status`,
          production: true,
        },
        {
          active: false,
          label: 'Historisk (andel)',
          id: 'levekar_lav-utdanning_historisk',
          heading: 'Personer 30–59 år med lav utdanning',
          help: 'Skifte i datagrunnlaget fra SSB mellom 2014 og 2015.',
          method: 'ratio',
          template: 'b',
          url: `${API}/levekar-lav-utdanning-historisk`,
          production: true,
        },
        {
          active: false,
          label: 'Historisk (antall)',
          id: 'levekar_lav-utdanning_historisk',
          heading: 'Personer 30–59 år med lav utdanning',
          help: 'Skifte i datagrunnlaget fra SSB mellom 2014 og 2015.',
          method: 'value',
          template: 'b',
          url: `${API}/levekar-lav-utdanning-historisk`,
          production: true,
        },
      ],
      about: `Lav utdanning inkluderer grunnskolenivå og de med ingen/uoppgitt utdanning. Fra og med 1.10.2014 har SSB gjort endringer i beregningsmetode over utdanningsnivå for innvandrere som står med uoppgitt i registeret. SSB bruker imputerte verdier på disse dataene. Dette har ført til brudd i tidsserien; data for 2014 og 2015 er ikke direkte sammenlignbare med tidligere perioder. <a href='http://www.ssb.no/utdanning/statistikker/utniv/aar/2016-06-20?fane=om#content#content'>Mer informasjon hos SSB</a>`,
    },
    {
      size: 'small',
      heading: 'Lavinntekt',
      map: {
        labels: ['Færre', 'Flere'],
        reverse: true,
        scale: [0, 0.3],
        method: 'ratio',
        url: `${API}/fattige-barnehusholdninger-status`,
      },
      production: true,
      tabs: [
        {
          active: false,
          label: 'Andel',
          id: 'levekar_fattige_andel',
          heading: 'Barnehusholdninger med lav inntekt',
          template: 'a',
          method: 'ratio',
          url: `${API}/fattige-barnehusholdninger-status`,
          production: true,
        },
        {
          active: false,
          label: 'Antall',
          id: 'levekar_fattige_andel',
          heading: 'Barnehusholdninger med lav inntekt',
          template: 'a',
          method: 'value',
          url: `${API}/fattige-barnehusholdninger-status`,
          production: true,
        },
        {
          active: false,
          label: 'Historisk (andel)',
          id: 'levekar_fattige_historisk',
          heading: 'Barnehusholdninger med lav inntekt',
          method: 'ratio',
          template: 'b',
          url: `${API}/fattige-barnehusholdninger-historisk`,
          production: true,
        },
        {
          active: false,
          label: 'Historisk (antall)',
          id: 'levekar_fattige_historisk',
          heading: 'Barnehusholdninger med lav inntekt',
          method: 'value',
          template: 'b',
          url: `${API}/fattige-barnehusholdninger-historisk`,
          production: true,
        },
      ],
      about: `Statistikken viser andel husholdninger med barn under 18 år med lav inntekt, etter EU-skala. Inntekten er korrigert for formue, det vil si at den viser husholdninger som har brutto finanskapital per forbruks­enhet under 1G.`,
    },
    {
      size: 'small',
      heading: 'Ikke fullført videregående skole',
      map: {
        labels: ['Færre', 'Flere'],
        url: `${API}/ikke-fullfort-vgs-status`,
        method: 'ratio',
        scale: [0.1, 0.5],
        reverse: true,
      },
      production: true,
      tabs: [
        {
          active: false,
          label: 'Andel',
          id: 'levekar_vgs_andel',
          heading: 'Personer 21–29 år som ikke har fullført videregående skole',
          template: 'a',
          method: 'ratio',
          url: `${API}/ikke-fullfort-vgs-status`,
          production: true,
        },
        {
          active: false,
          label: 'Antall',
          id: 'levekar_vgs_andel',
          heading: 'Personer 21–29 år som ikke har fullført videregående skole',
          template: 'a',
          method: 'value',
          url: `${API}/ikke-fullfort-vgs-status`,
          production: true,
        },
        {
          active: false,
          label: 'Historisk (andel)',
          id: 'levekar_vgs-historisk',
          heading: 'Personer 21–29 år som ikke har fullført videregående skole',
          template: 'b',
          method: 'ratio',
          url: `${API}/ikke-fullfort-vgs-historisk`,
          production: true,
        },

        {
          active: false,
          label: 'Historisk (antall)',
          id: 'levekar_vgs-historisk',
          heading: 'Personer 21–29 år som ikke har fullført videregående skole',
          template: 'b',
          method: 'value',
          url: `${API}/ikke-fullfort-vgs-historisk`,
          production: true,
        },
      ],
    },
    {
      size: 'small',
      heading: 'Dødelighet',
      map: {
        labels: ['Lavere dødsrate', 'Høyere dødsrate'],
        url: `${API}/dodsrater-status`,
        scale: [0.09, 0.203],
        reverse: true,
        method: 'ratio',
        hidePercentSymbol: true,
      },
      production: true,
      tabs: [
        {
          active: false,
          label: 'Dødsrate',
          heading: 'Dødelighet for personer 50–74 år',
          id: 'levekar_dodsrater_status_andel',
          template: 'a',
          method: 'ratio',
          url: `${API}/dodsrater-status`,
          production: true,
          hidePercentSymbol: true,
        },
      ],
    },
    {
      size: 'small',
      heading: 'Ikke sysselsatte',
      map: {
        labels: ['Færre ikke-sysselsatte', 'Flere ikke-sysselsatte'],
        url: `${API}/levekar-ikke-sysselsatte-status`,
        scale: [0.09, 0.352],
        method: 'ratio',
        reverse: true,
      },
      production: true,
      tabs: [
        {
          active: false,
          label: 'Antall',
          id: 'levekaar_ikke_sysselsatte_status_antall',
          heading: 'Ikke sysselsatte 30–59 år',
          template: 'a',
          method: 'value',
          url: `${API}/levekar-ikke-sysselsatte-status`,
          production: true,
        },
        {
          active: false,
          label: 'Andel',
          id: 'levekaar_ikke_sysselsatte_status_andel',
          heading: 'Ikke sysselsatte 30–59 år',
          template: 'a',
          method: 'ratio',
          url: `${API}/levekar-ikke-sysselsatte-status`,
          production: true,
        },
        {
          active: false,
          label: 'Historisk (antall)',
          id: 'levekaar_ikke_sysselsatte_historisk_antall',
          heading: 'Ikke sysselsatte 30–59 år',
          template: 'b',
          method: 'value',
          url: `${API}/levekar-ikke-sysselsatte-historisk`,
          production: true,
        },
        {
          active: false,
          label: 'Historisk (andel)',
          id: 'levekaar_ikke_sysselsatte_historisk_andel',
          heading: 'Ikke sysselsatte 30–59 år',
          template: 'b',
          method: 'ratio',
          url: `${API}/levekar-ikke-sysselsatte-historisk`,
          production: true,
        },
      ],
    },
    {
      size: 'small',
      heading: 'Kort botid',
      map: {
        labels: ['Færre ikke-vestlige innvandrere', 'Flere ikke-vestlige innvandrere'],
        url: `${API}/levekar-innvandrere-ikke-vestlige-kort-status`,
        scale: [0, 0.058],
        method: 'ratio',
        reverse: true,
      },
      production: true,
      tabs: [
        {
          active: false,
          label: 'Antall',
          id: 'levekaar_innvandrere_ikke_vestlige_kort_status_antall',
          heading: 'Innvandrere fra Asia, Afrika, Latin-Amerika og Øst-Europa utenfor EU med botid kortere enn fem år',
          template: 'a',
          method: 'value',
          url: `${API}/levekar-innvandrere-ikke-vestlige-kort-status`,
          production: true,
        },
        {
          active: false,
          label: 'Andel',
          id: 'levekaar_innvandrere_ikke_vestlige_kort_status_andel',
          heading: 'Innvandrere fra Asia, Afrika, Latin-Amerika og Øst-Europa utenfor EU med botid kortere enn fem år',
          template: 'a',
          method: 'ratio',
          url: `${API}/levekar-innvandrere-ikke-vestlige-kort-status`,
          production: true,
        },
        {
          active: false,
          label: 'Historisk (antall)',
          id: 'levekar_innvandrere_ikke_vestlige_kort_historisk_antall',
          heading: 'Innvandrere fra Asia, Afrika, Latin-Amerika og Øst-Europa utenfor EU med botid kortere enn fem år',
          template: 'b',
          method: 'value',
          url: `${API}/levekar-innvandrere-ikke-vestlige-kort-historisk`,
          production: true,
        },
        {
          active: false,
          label: 'Historisk (andel)',
          id: 'levekar_innvandrere_ikke_vestlige_kort_historisk_andel',
          heading: 'Innvandrere fra Asia, Afrika, Latin-Amerika og Øst-Europa utenfor EU med botid kortere enn fem år',
          template: 'b',
          method: 'ratio',
          url: `${API}/levekar-innvandrere-ikke-vestlige-kort-historisk`,
          production: true,
        },
      ],
    },
    {
      size: 'small',
      heading: 'Trangboddhet',
      production: true,
      map: {
        labels: ['Færre trangbodde', 'Flere trangbodde'],
        url: `${API}/levekar-trangbodde-status`,
        scale: [0.051, 0.465],
        method: 'ratio',
        reverse: true,
      },
      tabs: [
        {
          active: false,
          label: 'Andel',
          id: 'levekar_trangbodde_status',
          heading: 'Trangbodde husholdninger',
          template: 'a',
          method: 'ratio',
          url: `${API}/levekar-trangbodde-status`,
          production: true,
        },
        {
          active: false,
          label: 'Antall',
          id: 'levekar_trangbodde_status',
          heading: 'Trangbodde husholdninger',
          template: 'a',
          method: 'value',
          url: `${API}/levekar-trangbodde-status`,
          production: true,
        },
        {
          active: false,
          label: 'Historisk (andel)',
          id: 'levekar_trangbodde_historisk',
          heading: 'Trangbodde husholdninger',
          method: 'ratio',
          template: 'b',
          url: `${API}/levekar-trangbodde-historisk`,
          production: true,
        },
        {
          active: false,
          label: 'Historisk (antall)',
          id: 'levekar_trangbodde_historisk',
          heading: 'Trangbodde husholdninger',
          method: 'value',
          template: 'b',
          url: `${API}/levekar-trangbodde-historisk`,
          production: true,
        },
      ],
    },
    {
      size: 'small',
      heading: 'Redusert funksjonsevne',
      production: true,
      map: {
        labels: ['Færre med redusert funksjonsevne', 'Flere med redusert funksjonsevne'],
        url: `${API}/levekar-redusert-funksjonsevne-status`,
        scale: [0.065, 0.239],
        reverse: true,
        method: 'ratio',
      },
      tabs: [
        {
          active: false,
          label: 'Andel',
          id: 'levekar_redusert_funksjonsevne_status_andel',
          heading: 'Personer 16–66 år med redusert funksjonsevne',
          template: 'a',
          method: 'ratio',
          url: `${API}/levekar-redusert-funksjonsevne-status`,
          production: true,
        },
        {
          active: false,
          label: 'Antall',
          id: 'levekar_redusert_funksjonsevne_status_antall',
          heading: 'Personer 16–66 år med redusert funksjonsevne',
          template: 'a',
          method: 'value',
          url: `${API}/levekar-redusert-funksjonsevne-status`,
          production: true,
        },
        {
          active: false,
          label: 'Historisk (andel)',
          id: 'levekar_redusert_funksjonsevne_historisk_andel',
          heading: 'Personer 16–66 år med redusert funksjonsevne',
          method: 'ratio',
          template: 'b',
          url: `${API}/levekar-redusert-funksjonsevne-historisk`,
          production: true,
        },
        {
          active: false,
          label: 'Historisk (antall)',
          id: 'levekar_redusert_funksjonsevne_historisk_antall',
          heading: 'Personer 16–66 år med redusert funksjonsevne',
          method: 'value',
          template: 'b',
          url: `${API}/levekar-redusert-funksjonsevne-historisk`,
          production: true,
        },
      ],
    },
  ],
  options: {
    kategori: 'Levekår',
    tema: 'Levekårs&shy;indikatorer',
    bgImage: `${baseUrl}/img/levekaar`,
    txtColor: 'rgb(244, 206, 138)',
  },
  related: ['husholdninger', 'innvandrerbefolkningen', 'trangboddhet'],
};
