import { apiUrl, baseUrl } from '../../util/config';

const API = `${apiUrl}/api/dataset`;

export default {
  text: 'Trangboddhet',
  value: 'trangboddhet',
  production: true,
  cards: [
    {
      size: 'large',
      heading: 'Trangbodde husstander',
      production: null,
      tabs: [
        {
          active: false,
          label: 'Status',
          template: 'j',
          heading: 'Husholdninger fordelt etter antall rom per person',
          url: `${baseUrl}/trangboddhet.json`,
          method: 'ratio',
          production: true,
        },

        {
          active: false,
          label: 'Historisk (andel)',
          template: 'b',
          heading: 'Husholdninger fordelt etter antall rom per person',
          url: `${API}/trangboddhet-alle-historisk`,
          method: 'ratio',
          production: true,
        },
        {
          active: false,
          label: 'Historisk (antall)',
          template: 'b',
          heading: 'Husholdninger fordelt etter antall rom per person',
          url: `${API}/trangboddhet-alle-historisk`,
          method: 'value',
          production: true,
        },
      ],
    },
    {
      size: 'large',
      heading: 'Trangbodde husstander',
      production: true,
      tabs: [
        {
          active: false,
          label: 'Status',
          template: 'j',
          heading: 'Husholdninger fordelt etter antall rom per person',
          url: `${API}/trangboddhet-alle-status`,
          method: 'ratio',
          production: true,
        },

        {
          active: false,
          label: 'Historisk (andel)',
          template: 'c',
          heading: 'Husholdninger fordelt etter antall rom per person',
          url: `${API}/trangboddhet-alle-historisk`,
          method: 'ratio',
          production: true,
        },
        {
          active: false,
          label: 'Historisk (antall)',
          template: 'c',
          heading: 'Husholdninger fordelt etter antall rom per person',
          url: `${API}/trangboddhet-alle-historisk`,
          method: 'value',
          production: true,
        },
      ],
    },
    {
      size: 'small',
      heading: 'Under 0,5 rom per person',
      map: {
        labels: ['Lav andel', 'Høy andel'],
        method: 'ratio',
        heading: 'Husstander med under 0,5 rom per person',
        reverse: true,
        scale: [0.018, 0.14],
        url: `${API}/trangboddhet-under05-status`,
      },
      production: null,
      tabs: [
        {
          active: false,
          label: 'Andel',
          template: 'a',
          heading: 'Husholdninger med under 0,5 rom per person',
          url: `${API}/trangboddhet-under05-status`,
          method: 'ratio',
          production: true,
        },
        {
          active: false,
          label: 'Antall',
          template: 'a',
          heading: 'Husholdninger med under 0,5 rom per person',
          url: `${API}/trangboddhet-under05-status`,
          method: 'value',
          production: true,
        },
        {
          active: false,
          label: 'Historisk (andel)',
          template: 'b',
          heading: 'Husholdninger med under 0,5 rom per person',
          url: `${API}/trangboddhet-under05-historisk`,
          method: 'ratio',
          production: true,
        },
        {
          active: false,
          label: 'Historisk (antall)',
          template: 'b',
          heading: 'Husholdninger med under 0,5 rom per person',
          url: `${API}/trangboddhet-under05-historisk`,
          method: 'value',
          production: true,
        },
      ],
    },

    {
      size: 'small',
      heading: '0,5–0,9 rom per person',
      map: {
        labels: ['Lav andel', 'Høy andel'],
        method: 'ratio',
        reverse: true,
        scale: [0.035, 0.21],
        url: `${API}/trangboddhet-05-09-status`,
      },
      production: null,
      tabs: [
        {
          active: false,
          label: 'Andel',
          template: 'a',
          heading: 'Husholdninger med 0,5–0,9 rom per person',
          url: `${API}/trangboddhet-05-09-status`,
          method: 'ratio',
          production: true,
        },
        {
          active: false,
          label: 'Antall',
          template: 'a',
          heading: 'Husholdninger med 0,5–0,9 rom per person',
          url: `${API}/trangboddhet-05-09-status`,
          method: 'value',
          production: true,
        },
        {
          active: false,
          label: 'Historisk (andel)',
          template: 'b',
          heading: 'Husholdninger med 0,5–0,9 rom per person',
          url: `${API}/trangboddhet-05-09-historisk`,
          method: 'ratio',
          production: true,
        },
        {
          active: false,
          label: 'Historisk (antall)',
          template: 'b',
          heading: 'Husholdninger med 0,5–0,9 rom per person',
          url: `${API}/trangboddhet-05-09-historisk`,
          method: 'value',
          production: true,
        },
      ],
    },

    {
      size: 'small',
      heading: '1–1,9 rom per person',
      map: {
        labels: ['Lav andel', 'Høy andel'],
        method: 'ratio',
        reverse: true,
        scale: [0.268, 0.475],
        url: `${API}/trangboddhet-10-19-status`,
      },
      production: null,
      tabs: [
        {
          active: false,
          label: 'Andel',
          template: 'a',
          heading: 'Husholdninger med 1–1,9 rom per person',
          url: `${API}/trangboddhet-10-19-status`,
          method: 'ratio',
          production: true,
        },
        {
          active: false,
          label: 'Antall',
          template: 'a',
          heading: 'Husholdninger med 1–1,9 rom per person',
          url: `${API}/trangboddhet-10-19-status`,
          method: 'value',
          production: true,
        },
        {
          active: false,
          label: 'Historisk (andel)',
          template: 'b',
          heading: 'Husholdninger med 1–1,9 rom per person',
          url: `${API}/trangboddhet-10-19-historisk`,
          method: 'ratio',
          production: true,
        },
        {
          active: false,
          label: 'Historisk (antall)',
          template: 'b',
          heading: 'Husholdninger med 1–1,9 rom per person',
          url: `${API}/trangboddhet-10-19-historisk`,
          method: 'value',
          production: true,
        },
      ],
    },

    {
      size: 'small',
      heading: '2 rom eller flere per person',
      map: {
        labels: ['Lav andel', 'Høy andel'],
        method: 'ratio',
        reverse: true,
        scale: [0.34, 0.6],
        url: `${API}/trangboddhet-over-2-status`,
      },
      production: null,
      tabs: [
        {
          active: false,
          label: 'Andel',
          template: 'a',
          heading: 'Husholdninger med 2 rom eller flere per person',
          url: `${API}/trangboddhet-over-2-status`,
          method: 'ratio',
          production: true,
        },
        {
          active: false,
          label: 'Antall',
          template: 'a',
          heading: 'Husholdninger med 2 rom eller flere per person',
          url: `${API}/trangboddhet-over-2-status`,
          method: 'value',
          production: true,
        },
        {
          active: false,
          label: 'Historisk (andel)',
          template: 'b',
          heading: 'Husholdninger med 2 rom eller flere per person',
          url: `${API}/trangboddhet-over-2-historisk`,
          method: 'ratio',
          production: true,
        },
        {
          active: false,
          label: 'Historisk (antall)',
          template: 'b',
          heading: 'Husholdninger med 2 rom eller flere per person',
          url: `${API}/trangboddhet-over-2-historisk`,
          method: 'value',
          production: true,
        },
      ],
    },
  ],
  options: {
    kategori: 'Bomiljø',
    tema: 'Trangboddhet',
    bgImage: `${baseUrl}/img/trangboddhet`,
    txtColor: 'rgb(199, 247, 201)',
  },
  related: ['boligpriser', 'levekaar', 'eieform'],
};
